In [54]:
import pandas as pd
import numpy as np
import nltk

In [55]:
temp_df = pd.read_csv(r"C:\Users\Vanshika Bisht\Downloads\zomato_reviews.csv")

In [56]:
df = temp_df.iloc[:10000]

In [57]:
df.head()

review_id  rating  \
0  90749778-cd88-4c19-8b12-1fce7e7d82f8       4   
1  aa848bb6-d242-4a7e-831e-4f21e2e60c6e       1   
2  4f888388-9f28-44a4-8601-491a87035e53       5   
3  490a16b3-aacf-4204-bdcb-ffdbf04add72       1   
4  0090a503-13b8-4741-a7c0-42e811244563       5   

                                         review_text          review_date  \
0  kindly requesting to return change . we are fo...  2025-11-27 08:15:26   
1         Hiked prices, packing and platform charges  2025-11-27 08:08:31   
2                                      good discount  2025-11-27 04:20:28   
3  Zomato in its initial days was too good, but c...  2025-11-27 03:34:38   
4                                   good application  2025-11-27 02:50:58   

   helpful  
0        0  
1        0  
2        0  
3        0  
4        0

In [58]:
df.shape

(10000, 5)

In [59]:
df = df[['review_text', 'rating']]

In [60]:
df.review_text[0]

'kindly requesting to return change . we are forced to let go of Rs 100. after paying all zomato charges plus to delivery man .This is broad daylight robbery.'

In [61]:
df.isnull().sum()

review_text    0
rating         0
dtype: int64

In [62]:
df.duplicated().sum()

np.int64(1063)

In [63]:
import nltk
from nltk.corpus import stopwords
sw_list = stopwords.words('english')

In [64]:
df['review_text'] = df['review_text'].apply(lambda x:[item for item in x.split() if item not in sw_list]).apply(lambda x:" ".join(x))

In [65]:
x = df.iloc[: , 0:1]
y = df['rating']

In [66]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()

In [67]:
y=  encoder.fit_transform(y)

In [68]:
from sklearn.model_selection import train_test_split


In [69]:
x_train , x_test , y_train , y_test = train_test_split(x,y,test_size=0.2 , random_state=42)

In [70]:
x_train.shape , y_train.shape , x_test.shape , y_test.shape

((8000, 1), (8000,), (2000, 1), (2000,))

In [71]:
x_train

review_text
9254                            good service experience
1561                    Very Smooth Service I like much
1670  It issue asks pnr no. deliveries near station ...
6087                                        good others
6669                 looks good I tell delivering order
...                                                 ...
5734                               good discount.......
5191                zomato good comes 50 % upto 40 60 👀
5390  never use app Zomato agent deliver order updat...
860   23-Nov-2025 update - happy Zomato. still happy...
7270  fraudulent practice continuously going sweets ...

[8000 rows x 1 columns]

In [72]:
from sklearn.feature_extraction.text import CountVectorizer
cv= CountVectorizer()

In [73]:
x_train1 = cv.fit_transform(x_train['review_text']).toarray()
x_test1 = cv.transform(x_test['review_text']).toarray()

In [74]:
x_train1.shape , x_test1.shape

((8000, 6477), (2000, 6477))

In [75]:
from sklearn.naive_bayes import MultinomialNB , GaussianNB , BernoulliNB
from sklearn.metrics import classification_report , confusion_matrix , accuracy_score

In [76]:
def model(model):
  model.fit(x_train1, y_train)
  y_pred = model.predict(x_test1)
  print(classification_report(y_test , y_pred))
  print(confusion_matrix(y_test , y_pred))
  print(accuracy_score(y_test , y_pred))


In [77]:
model(MultinomialNB())

              precision    recall  f1-score   support

           0       0.78      0.90      0.83       459
           1       0.00      0.00      0.00        44
           2       1.00      0.02      0.03        62
           3       0.52      0.12      0.20       272
           4       0.79      0.95      0.86      1163

    accuracy                           0.78      2000
   macro avg       0.62      0.40      0.39      2000
weighted avg       0.74      0.78      0.72      2000

[[ 411    0    0    9   39]
 [  28    0    0    5   11]
 [  28    0    1    5   28]
 [  21    0    0   34  217]
 [  40    0    0   13 1110]]
0.778


C:\Users\Sahil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sahil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\Sahil\anaconda3\Lib\site-packages\sklearn\metrics\_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


In [78]:
model(GaussianNB())

              precision    recall  f1-score   support

           0       0.66      0.58      0.62       459
           1       0.00      0.00      0.00        44
           2       0.02      0.34      0.04        62
           3       0.13      0.14      0.13       272
           4       0.62      0.15      0.24      1163

    accuracy                           0.25      2000
   macro avg       0.29      0.24      0.21      2000
weighted avg       0.53      0.25      0.30      2000

[[266  23  96  25  49]
 [ 23   0  11   6   4]
 [ 25   2  21   8   6]
 [ 28   9 152  37  46]
 [ 60  30 699 205 169]]
0.2465


In [79]:
model(BernoulliNB())

              precision    recall  f1-score   support

           0       0.78      0.61      0.69       459
           1       0.00      0.00      0.00        44
           2       0.00      0.00      0.00        62
           3       0.32      0.08      0.13       272
           4       0.71      0.96      0.82      1163

    accuracy                           0.71      2000
   macro avg       0.36      0.33      0.33      2000
weighted avg       0.64      0.71      0.65      2000

[[ 282    0    0   14  163]
 [  22    0    1    4   17]
 [  17    0    0    7   38]
 [  17    0    1   23  231]
 [  23    1    0   24 1115]]
0.71


In [80]:
from sklearn.ensemble import RandomForestClassifier


In [81]:
model(RandomForestClassifier())

              precision    recall  f1-score   support

           0       0.76      0.87      0.81       459
           1       0.17      0.02      0.04        44
           2       0.00      0.00      0.00        62
           3       0.42      0.13      0.20       272
           4       0.78      0.92      0.85      1163

    accuracy                           0.75      2000
   macro avg       0.43      0.39      0.38      2000
weighted avg       0.69      0.75      0.71      2000

[[ 400    1    2    2   54]
 [  31    1    2    0   10]
 [  23    3    0    6   30]
 [  27    1    6   35  203]
 [  44    0    6   41 1072]]
0.754


In [82]:
cv1 = CountVectorizer(max_features=3000)

In [83]:
x_train_bow = cv1.fit_transform(x_train['review_text'])
x_test_bow = cv1.fit(x_test['review_text'])

In [84]:
x_train_bow.shape

(8000, 3000)

In [85]:
def model(model):
  model.fit(x_train_bow, y_train)
  y_pred = model.predict(x_test_bow)
  print(accuracy_score(y_test , y_pred))
  print(classification_report(y_test , y_pred))
  print(confusion_matrix(y_test , y_pred))


In [86]:
cv2 = CountVectorizer(ngram_range=(1,2))


In [87]:
x_train_bow = cv2.fit_transform(x_train['review_text']).toarray()
x_test_bow = cv2.transform(x_test['review_text']).toarray()

tf-idf

In [89]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [90]:
tf= TfidfVectorizer()

In [91]:
x_train_tf = tf.fit_transform(x_train['review_text'])
x_test_tf = tf.transform(x_test['review_text'])

In [92]:
x_train_tf.shape

(8000, 6477)

In [93]:
model = RandomForestClassifier()
model.fit(x_train_tf, y_train)
y_pred = model.predict(x_test_tf)
print(classification_report(y_test , y_pred))
print(confusion_matrix(y_test , y_pred))
print(accuracy_score(y_test , y_pred))

KeyboardInterrupt: 